name: Build and Release Debian Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        with:
          package-name: "grub2-theme-hamonikr"
          version: ${{ github.ref_name }}
          maintainer: "Kevin Kim <chaeya@gmail.com>"
          architecture: "all"
          section: "misc"
          priority: "optional"
          description: "grub2 theme"

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: ./*.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: debian-package
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
